select id,
       date_diff,
       id_session,
       date,
       results_total,
       results_on_page,
       service_flags,
       search_source,
       elastic_query_time_ms,
       q_flags,
       q_kw,
       q_id_region,
       q_txt_region,
       q_radius_km,
       q_age,
       q_salary_gte,
       kw_hash,
       query_hash,
       q_job_type,
       id_account,
       elastic_search_time_ms,
       cdomain_hash64,
       elastic_took_time_ms,
       q_remote_type,
       q_hashtags,
       search_type
from public.session_search
where date_diff = %(date)s
;