SET NOCOUNT ON;

select id,
       id_similar_group,
       id_project,
       date_created,
       date_updated,
       date_expired,
       title,
       company_name,
       salary_val1,
       salary_val2,
       id_currency,
       id_salary_rate,
       job_type1,
       job_type2,
       id_language,
       html_desc_mode,
       checksum,
       cast(is_pdf as smallint) as is_pdf,
       emails,
       emails_src,
       lang_title,
       lang_text,
       company_name_hash64,
       cast(partial_update as smallint) as partial_update,
       telephones,
       phone_src,
       state_flags,
       remote_type,
       text_hash64,
       html_hash64,
       cast(need_update_text as smallint) as need_update_text,
       segmentation_tag_hash64,
       id_category
from dbo.job
;