internal_dbs = {
    "conversions_service_info": {
        "conversions_service_nl": {
            "cluster": "nl",
            "host": "10.0.1.170",
            "dbs": [
                "conversions-service",
            ],
            "db_type": "postgresql",
            "credential_key": "internal",
        },
        "conversions_service_us": {
            "cluster": "us",
            "host": "192.168.1.77",
            "dbs": [
                "conversions-service",
            ],
            "db_type": "postgresql",
            "credential_key": "conversion",
        },
    },
    "soska_info": {
        "host": "lager.jooble.com",
        "dbs": [
            "soska",
            "Devman",
        ],
        "db_type": "mssql",
        "credential_key": "soska",
    },
    "warehouse_jo": {
        "host": "192.168.3.201",
        "dbs": [
            "Marketing",
            "PublicStatistic",
            "Google",
            "Reddit",
            "Facebook",
        ],
        "db_type": "mssql",
        "credential_key": "internal",
    },
    "warehouse_137": {
        "host": "10.0.0.137",
        "dbs": [
            "dwh",
        ],
        "db_type": "postgresql",
        "credential_key": "internal",
    },
    "employer_account": {
        "host": "10.0.0.89",
        "dbs": [
            "employer_account",
            "employer_statistics",
            "payment_service",

        ],
        "db_type": "mariadb",
        "credential_key": "internal",
    },
    "ea_crm_flowchart": {
        "host": "10.0.1.151",
        "dbs": [
            "EA_CRM",
            "DteFlowchart",
            "ProfileCrm",
        ],
        "db_type": "mssql",
        "credential_key": "internal",
    },
    "seo_server": {
        "host": "10.0.1.62",
        "dbs": [
            "BigQuery",
            "similarweb",
            "SearchConsole",
            "SeoQueries",
            "Seo_tests",
        ],
        "db_type": "mssql",
        "credential_key": "seo_server",
    },
    "1c": {
        "host": "10.26.0.140",
        "dbs": [
            "invoiceReport",
        ],
        "db_type": "mssql",
        "credential_key": "1c",
    },
    "amt_projects": {
        "host": "10.0.0.143",
        "dbs": [
            "AMT_projects",
        ],
        "db_type": "postgresql",
        "credential_key": "repstat",
    },
    "history_db_info": {
        "nl-history_dbs_new": {
            "host": "10.0.3.189",
            "dbs": [
                'fr',
                'uk',
                'de',
                'at',
                'be',
                'ch',
                'nl',
                'pl',
                'ro',
                'hu',
                'rs',
            ],
            "db_type": "postgresql",
            "credential_key": "internal",
        },
        # "nl-history_dbs_old": {
        #     "host": "10.0.0.196",
        #     "dbs": [
        #         "fr",
        #         "uk",
        #         "de",
        #         # 'at',
        #         # 'be',
        #         # 'ch',
        #         # 'nl',
        #         # 'pl',
        #         # 'ro',
        #         # 'hu'
        #     ],
        #     "db_type": "postgresql",
        #     "credential_key": "internal",
        # },
        "us-history_dbs": {
            "host": "us-history-db1.jooble.com",
            "dbs": [
                "ca",
                "us",
            ],
            "db_type": "postgresql",
            "credential_key": "internal",
        },
        # 'fr-history_dbs': {
        #     'host': '10.0.1.32',
        #     'dbs': [
        #         'fr',
        #     ],
        #     "db_type": "postgresql",
        #     "credential_key": "internal",
        # },
    },
}


prod_dbs = [
    {
        "country": "de",
        "country_id": 2,
        "host": "10.0.0.136",
        "database": "Job_DE",
    },
    {
        "country": "at",
        "country_id": 13,
        "host": "nl-at-job-db.jooble.com",
        "database": "Job_AT",
    },
    {
        "country": "pt",
        "country_id": 59,
        "host": "nl-pt-job-db.jooble.com",
        "database": "Job_PT",
    },
    {
        "country": "es",
        "country_id": 12,
        "host": "nl-es-job-db.jooble.com",
        "database": "Job_ES",
    },
    {
        "country": "qa",
        "country_id": 65,
        "host": "nl-qa-job-db.jooble.com",
        "database": "Job_QA",
    },
    {
        "country": "it",
        "country_id": 19,
        "host": "nl-it-job-db.jooble.com",
        "database": "Job_IT",
    },
    {
        "country": "in",
        "country_id": 18,
        "host": "nl-in-job-db.jooble.com",
        "database": "Job_IN",
    },
    {
        "country": "nl",
        "country_id": 20,
        "host": "nl-nl-job-db.jooble.com",
        "database": "Job_NL",
    },
    {
        "country": "hr",
        "country_id": 31,
        "host": "nl-hr-job-db.jooble.com",
        "database": "Job_HR",
    },
    {
        "country": "az",
        "country_id": 56,
        "host": "nl-az-job-db.jooble.com",
        "database": "Job_AZ",
    },
    {
        "country": "kw",
        "country_id": 67,
        "host": "nl-kw-job-db.jooble.com",
        "database": "Job_KW",
    },
    {
        "country": "bh",
        "country_id": 68,
        "host": "nl-bh-job-db.jooble.com",
        "database": "Job_BH",
    },
    {
        "country": "eg",
        "country_id": 69,
        "host": "nl-eg-job-db.jooble.com",
        "database": "Job_EG",
    },
    {
        "country": "ma",
        "country_id": 70,
        "host": "nl-ma-job-db.jooble.com",
        "database": "Job_MA",
    },
    {
        "country": "ie",
        "country_id": 61,
        "host": "nl-ie-job-db.jooble.com",
        "database": "Job_IE",
    },
    {
        "country": "kz",
        "country_id": 32,
        "host": "nl-kz-job-db.jooble.com",
        "database": "Job_KZ",
    },
    {
        "country": "ng",
        "country_id": 37,
        "host": "nl-ng-job-db.jooble.com",
        "database": "Job_NG",
    },
    {
        "country": "pk",
        "country_id": 45,
        "host": "nl-pk-job-db.jooble.com",
        "database": "Job_PK",
    },
    {
        "country": "ro",
        "country_id": 11,
        "host": "nl-ro-job-db.jooble.com",
        "database": "Job_RO",
    },
    {
        "country": "rs",
        "country_id": 34,
        "host": "nl-rs-job-db.jooble.com",
        "database": "Job_RS",
    },
    {
        "country": "uk",
        "country_id": 3,
        "host": "10.0.0.69",
        "database": "Job_UK",
    },
    {
        "country": "uz",
        "country_id": 71,
        "host": "nl-uz-job-db.jooble.com",
        "database": "Job_UZ",
    },
    {
        "country": "ae",
        "country_id": 64,
        "host": "nl-ae-job-db.jooble.com",
        "database": "Job_AE",
    },
    {
        "country": "sa",
        "country_id": 66,
        "host": "nl-sa-job-db.jooble.com",
        "database": "Job_SA",
    },
    {
        "country": "ch",
        "country_id": 16,
        "host": "nl-ch-job-db.jooble.com",
        "database": "Job_CH",
    },
    {
        "country": "ua",
        "country_id": 1,
        "host": "nl-ua-job-db.jooble.com",
        "database": "Job_UA",
    },
    {
        "country": "fi",
        "country_id": 57,
        "host": "nl-fi-job-db.jooble.com",
        "database": "Job_FI",
    },
    {
        "country": "bg",
        "country_id": 30,
        "host": "nl-bg-job-db.jooble.com",
        "database": "Job_BG",
    },
    {
        "country": "ba",
        "country_id": 58,
        "host": "nl-ba-job-db.jooble.com",
        "database": "Job_BA",
    },
    {
        "country": "tr",
        "country_id": 21,
        "host": "nl-tr-job-db.jooble.com",
        "database": "Job_TR",
    },
    {
        "country": "fr",
        "country_id": 4,
        "host": "nl-fr-job-db.jooble.com",
        "database": "Job_FR",
    },
    {
        "country": "be",
        "country_id": 14,
        "host": "nl-be-job-db.jooble.com",
        "database": "Job_BE",
    },
    {
        "country": "no",
        "country_id": 33,
        "host": "nl-no-job-db.jooble.com",
        "database": "Job_NO",
    },
    {
        "country": "dk",
        "country_id": 60,
        "host": "nl-dk-job-db.jooble.com",
        "database": "Job_DK",
    },
    {
        "country": "sk",
        "country_id": 26,
        "host": "nl-sk-job-db.jooble.com",
        "database": "Job_SK",
    },
    {
        "country": "cz",
        "country_id": 17,
        "host": "nl-cz-job-db.jooble.com",
        "database": "Job_CZ",
    },
    {
        "country": "gr",
        "country_id": 25,
        "host": "nl-gr-job-db.jooble.com",
        "database": "Job_GR",
    },
    {
        "country": "hu",
        "country_id": 10,
        "host": "nl-hu-job-db.jooble.com",
        "database": "Job_HU",
    },
    {
        "country": "se",
        "country_id": 35,
        "host": "nl-se-job-db.jooble.com",
        "database": "Job_SE",
    },
    {
        "country": "pl",
        "country_id": 9,
        "host": "nl-pl-job-db.jooble.com",
        "database": "Job_PL",
    },
    {
        "country": "ph",
        "country_id": 44,
        "host": "us-ph-job-db.jooble.com",
        "database": "Job_PH",
    },
    {
        "country": "hk",
        "country_id": 42,
        "host": "us-hk-job-db.jooble.com",
        "database": "Job_HK",
    },
    {
        "country": "kr",
        "country_id": 43,
        "host": "us-kr-job-db.jooble.com",
        "database": "Job_KR",
    },
    {
        "country": "cn",
        "country_id": 41,
        "host": "us-cn-job-db.jooble.com",
        "database": "Job_CN",
    },
    {
        "country": "co",
        "country_id": 24,
        "host": "us-co-job-db.jooble.com",
        "database": "Job_CO",
    },
    {
        "country": "za",
        "country_id": 63,
        "host": "us-za-job-db.jooble.com",
        "database": "Job_ZA",
    },
    {
        "country": "ar",
        "country_id": 38,
        "host": "us-ar-job-db.jooble.com",
        "database": "Job_AR",
    },
    {
        "country": "au",
        "country_id": 51,
        "host": "us-au-job-db.jooble.com",
        "database": "Job_AU",
    },
    {
        "country": "br",
        "country_id": 15,
        "host": "us-br-job-db.jooble.com",
        "database": "Job_BR",
    },
    {
        "country": "cr",
        "country_id": 50,
        "host": "us-cr-job-db.jooble.com",
        "database": "Job_CR",
    },
    {
        "country": "my",
        "country_id": 62,
        "host": "us-my-job-db.jooble.com",
        "database": "Job_MY",
    },
    {
        "country": "tw",
        "country_id": 28,
        "host": "us-tw-job-db.jooble.com",
        "database": "Job_TW",
    },
    {
        "country": "ca",
        "country_id": 5,
        "host": "us-ca-job-db.jooble.com",
        "database": "Job_CA",
    },
    {
        "country": "th",
        "country_id": 27,
        "host": "us-th-job-db.jooble.com",
        "database": "Job_TH",
    },
    {
        "country": "sv",
        "country_id": 49,
        "host": "us-sv-job-db.jooble.com",
        "database": "Job_SV",
    },
    {
        "country": "pr",
        "country_id": 48,
        "host": "us-pr-job-db.jooble.com",
        "database": "Job_PR",
    },
    {
        "country": "jp",
        "country_id": 46,
        "host": "us-jp-job-db.jooble.com",
        "database": "Job_JP",
    },
    {
        "country": "pe",
        "country_id": 40,
        "host": "us-pe-job-db.jooble.com",
        "database": "Job_PE",
    },
    {
        "country": "ec",
        "country_id": 54,
        "host": "us-ec-job-db.jooble.com",
        "database": "Job_EC",
    },
    {
        "country": "sg",
        "country_id": 55,
        "host": "us-sg-job-db.jooble.com",
        "database": "Job_SG",
    },
    {
        "country": "us",
        "country_id": 6,
        "host": "us-us-job-db.jooble.com",
        "database": "Job_US",
    },
    {
        "country": "cl",
        "country_id": 23,
        "host": "us-cl-job-db.jooble.com",
        "database": "Job_CL",
    },
    {
        "country": "do",
        "country_id": 52,
        "host": "us-do-job-db.jooble.com",
        "database": "Job_DO",
    },
    {
        "country": "uy",
        "country_id": 53,
        "host": "us-uy-job-db.jooble.com",
        "database": "Job_UY",
    },
    {
        "country": "nz",
        "country_id": 36,
        "host": "us-nz-job-db.jooble.com",
        "database": "Job_NZ",
    },
    {
        "country": "mx",
        "country_id": 39,
        "host": "us-mx-job-db.jooble.com",
        "database": "Job_MX",
    },
    {
        "country": "id",
        "country_id": 7,
        "host": "us-id-job-db.jooble.com",
        "database": "Job_ID",
    },
]


repstat_dbs = {
    "us_cluster": {
        "host": "192.168.1.207",
        "dbs": [
            "cl",
            "id",
            "mx",
            "nz",
            "uy",
            "cn",
            "co",
            "hk",
            "kr",
            "ph",
            "za",
            "ar",
            "au",
            "br",
            "cr",
            "my",
            "tw",
            "ca",
            "jp",
            "pr",
            "sv",
            "th",
            "ec",
            "pe",
            "sg",
            "us",
            "do",
        ],
        "db_type": "postgresql",
        "credential_key": "repstat",
    },
    "nl_cluster": {
        "host": "10.0.1.65",
        "dbs": [
            "ch",
            "nl",
            "de",
            "cz",
            "hu",
            "fr",
            "at",
            "es",
            "it",
            "pt",
            "az",
            "bh",
            "eg",
            "hr",
            "kw",
            "ma",
            "ae",
            "ie",
            "kz",
            "ng",
            "pk",
            "qa",
            "ro",
            "rs",
            "sa",
            "uz",
            "ba",
            "be",
            "bg",
            "fi",
            "tr",
            "gr",
            "no",
            "se",
            "sk",
            "in",
            "ua",
            "pl",
            "uk",
            "dk",
        ],
        "db_type": "postgresql",
        "credential_key": "repstat",
    },
}


citus = {
    "nl_cluster": {
        "host": "10.0.2.145",
        "dbs": [
            "uk_statistic"
        ],
        "db_type": "postgresql",
        "credential_key": "citus",
    },
}


new_pg = {
    "nl_cluster": {
        "host": "10.0.2.143",
        "dbs": [
            "uk"
        ],
        "db_type": "postgresql",
        "credential_key": "new_pg",
    },
}


cloudberry = {
    "nl_cluster": {
        "host": "an-dwh.jooble.com",
        "dbs": [
            "dwh",
            "rs",
            "uk",
        ],
        "db_type": "postgresql",
        "credential_key": "cloudberry",
    },
}
