from dagster import Definitions

# IMPORT SCHEDULES, ASSETS, JOBS
from .jobs_schedules import *
from .sensors import *


# define all: op, assets, jobs and schedules
defs = Definitions(
    sensors=[
        monitor_all_jobs_sensor,
        apply_conversion_service_to_replica_sensor,
        seo_test_url_keyword_job_sensor,
        ext_stat_away_match_job_sensor,
        # adwords_to_compare_yesterday_job_sensor
    ],
    schedules=[
        schedule_seo_gfj_stat,
        schedule_undelivered_email_job,
        schedule_scan_flow_statistic,
        schedule_seo_matrix_stat_job,
        schedule_conversions_joveo,
        schedule_vacancy_job_history,
        # schedule_subscription_model,
        schedule_conversions_case,
        schedule_conversions_project_case,
        schedule_apply_conversion_service,
        schedule_apply_conversion_service_yesterday,
        # schedule_subscription_model_jobs,
        schedule_paid_ad_groups_cost_statistic,
        schedule_paid_ad_groups,
        schedule_paid_campaigns,
        schedule_paid_accounts,
        # schedule_subscription_model_funnel_full,
        schedule_paid_info_currency,
        schedule_facebook_adset,
        # schedule_subscription_model_metrics_raw,
        schedule_paid_campaign_channel,
        schedule_facebook_2018,
        schedule_campaign_cpa,
        schedule_auction_user_target_action,
        schedule_landing_callback_form,
        schedule_conversions_appcast,
        schedule_conversions_indeed,
        schedule_web_bigquery_statistic,
        schedule_web_bigquery_statistic_reload_two_days,
        schedule_web_bigquery_statistic_reload_us,
        schedule_ahrefs_organic_v3,
        schedule_ahrefs_metrics_extended_v3,
        # schedule_webmaster_full_agg,
        # schedule_m_ea_sales_usd_fakevsreal_revenue,
        # schedule_webmaster_statistic,
        schedule_adwords_yesterday,
        schedule_adwords_current_date,
        schedule_bing,
        schedule_paid_legend_labels_channel,
        schedule_balkans_employers,
        schedule_balkans_payments,
        schedule_balkans_trials,
        schedule_balkans_subscriptions_with_payments,
        schedule_balkans_click_on_try_agg,
        schedule_ea_seo_urls_potential,
        schedule_first_site_manager,
        schedule_devman_task,
        schedule_exclude_ppc_traffic_request,
        schedule_scan_flow_high_potential,
        schedule_scan_flow_low_potential,
        schedule_currency_source,
        schedule_invoice_row,
        schedule_crawler_stat,
        schedule_domain_responsible_snapshot,
        schedule_domains_per_user_daily,
        schedule_google_account,
        # schedule_google_ad_group,
        schedule_google_campaign,
        schedule_google_mcc,
        schedule_invoice_info_report,
        schedule_conversions,
        schedule_conversions_campaign,
        schedule_conversions_source,
        # schedule_reddit,
        schedule_amt_scan_weekly_goal,
        schedule_dic_seo_search_category,
        schedule_ppc_automatization_pmax_log,
        schedule_profile_crm_calls,
        schedule_profile_crm_order,
        schedule_facebook_adset_new,
        schedule_facebook_2025,
        schedule_seo_test_groups,
        schedule_balkans_competitor_scans_infostud,
        schedule_ea_job_to_uid_mapping,
        schedule_ea_job,
        schedule_ea_employer,
    ],
    assets=[],
    jobs=[
        seo_gfj_stat_job,
        undelivered_email_job,
        scan_flow_statistic_job,
        seo_matrix_stat_job,
        conversions_joveo_job,
        vacancy_job_history_job,
        # subscription_model_job,
        conversions_case_job,
        conversions_project_case_job,
        apply_conversion_service_job,
        apply_conversion_service_job_yesterday,
        # subscription_model_jobs_job,
        paid_ad_groups_cost_statistic_job,
        paid_ad_groups_job,
        paid_campaigns_job,
        paid_accounts_job,
        # subscription_model_funnel_full_job,
        paid_info_currency_job,
        facebook_adset_job,
        # subscription_model_metrics_raw_job,
        # yiv_to_dwh_job,
        paid_campaign_channel_job,
        facebook_2018_job,
        campaign_cpa_job,
        auction_user_target_action_job,
        landing_callback_form_job,
        conversions_indeed_job,
        conversions_appcast_job,
        web_bigquery_statistic_job,
        web_bigquery_statistic_reload_two_days_job,
        web_bigquery_statistic_reload_us_job,
        ahrefs_organic_v3_job,
        ahrefs_metrics_extended_v3_job,
        # webmaster_full_agg_job,
        # m_ea_sales_usd_fakevsreal_revenue_job,
        # webmaster_statistic_job,
        adwords_yesterday_job,
        adwords_current_date_job,
        bing_job,
        paid_legend_labels_channel_job,
        balkans_employers_job,
        balkans_payments_job,
        balkans_trials_job,
        balkans_subscriptions_with_payments_job,
        balkans_click_on_try_agg_job,
        ea_seo_urls_potential_job,
        first_site_manager_job,
        devman_task_job,
        exclude_ppc_traffic_request_job,
        scan_flow_high_potential_job,
        scan_flow_low_potential_job,
        currency_source_job,
        invoice_row_job,
        crawler_stat_job,
        domain_responsible_snapshot_job,
        domains_per_user_daily_job,
        google_account_job,
        # google_ad_group_job,
        google_campaign_job,
        google_mcc_job,
        invoice_info_report_job,
        conversions_job,
        conversions_campaign_job,
        conversions_source_job,
        # reddit_job,
        amt_scan_weekly_goal_job,
        dic_seo_search_category_job,
        ppc_automatization_pmax_log_job,
        profile_crm_calls_job,
        profile_crm_order_job,
        facebook_adset_new_job,
        facebook_2025_job,
        seo_test_groups_job,
        balkans_competitor_scans_infostud_job,
        ea_job_to_uid_mapping_job,
        ea_job_job,
        ea_employer_job,
    ],
)
