from dagster import Definitions
# IMPORT SENSORS
from .sensors import *

# IMPORT SCHEDULES, ASSETS, JOBS
from .jobs_schedules import *


# define all: op, assets, jobs and schedules
defs = Definitions(
    schedules=[
        schedule_auction_login_log,
        schedule_adv_revenue_ea_new,
        schedule_auction_campaign_job,
        schedule_jdp_away_clicks_today,
        # schedule_serp_campaign_rivals_agg,
        schedule_email_account_test,
        schedule_email_metric_daily,
        schedule_session_daily_agg,
        # schedule_bot_jdp_away_clicks_agg,
        # schedule_salary_page_click_daily_agg,
        schedule_impression_statistic_agg,
        schedule_email_account_test_settings,
        schedule_auction_click_statistic,
        schedule_auction_click_statistic_reload_us,
        schedule_auction_click_statistic_reload_last_month,
        schedule_auction_click_statistic_analytics,
        # schedule_jdp_away_clicks_agg,
        # schedule_jdp_away_clicks_agg_last_seven_days,
        schedule_seo_ab_prod_metrics,
        # schedule_ext_stat_away_match,
        schedule_additional_pages_click_daily_agg,
        schedule_info_region_other,
        schedule_account_agg,
        schedule_adv_revenue_by_placement_and_src,
        schedule_adv_revenue_by_placement_and_src_analytics_agg,
        schedule_funnel_agg,
        schedule_dic_info_project_discount,
        schedule_dic_info_project_discount_monthly,
        schedule_jobs_stat_hourly,
        # schedule_auction_external_stat,
        schedule_campaign_auto_esc_stopped,
        schedule_banner_stat_history,
        schedule_banner_filter,
        schedule_banner_info,
        schedule_banner_limit,
        schedule_info_currency_history,
        schedule_project_tracking_setting,
        schedule_conversion,
        schedule_project_job_type_agg,
        schedule_project_job_apply_agg,
        schedule_conversion_action,
        schedule_session_test_agg,
        schedule_push_firebase_subscriptions,
        # schedule_push_sent,
        schedule_general_feed_ignored_projects,
        # schedule_general_feed_ignored_companies,
        schedule_user_budget_log,
        schedule_campaign_log_yesterday_date,
        schedule_campaign_log_current_date,
        schedule_user_log,
        schedule_banner_stat_today,
        # schedule_innovation_adsy_project,
        schedule_session_feature,
        # schedule_field_from_source_daily,
        schedule_campaign,
        schedule_campaign_feature,
        schedule_client_daily_settings,
        schedule_auction_site,
        schedule_auction_site_manager,
        schedule_auction_user,
        schedule_info_currency_job,
        schedule_info_project_job,
        schedule_u_traffic_source_job,
        schedule_scheduled_operation,
        schedule_auction_job_multiplication,
        schedule_session_test,
    ],
    assets=[],
    jobs=[
        login_log_job,
        adv_revenue_ea_new_job,
        auction_campaign_job,
        u_traffic_source_job,
        info_project_job,
        info_currency_job,
        jdp_away_clicks_today_job,
        serp_campaign_rivals_agg_job,
        email_account_test_job,
        email_metric_daily_job,
        session_daily_agg_job,
        scroll_click_position_agg_job,
        # PRD_bot_jdp_away_clicks_agg_job,
        # PRD_salary_page_click_daily_agg_job,
        PRD_impression_statistic_agg_job,
        session_test_agg_job,
        push_firebase_subscriptions_job,
        # push_sent_job,
        email_account_test_settings_job,
        auction_click_statistic_job,
        auction_click_statistic_reload_us_job,
        auction_click_statistic_reload_last_month_job,
        auction_click_statistic_analytics_job,
        jdp_away_clicks_agg_job,
        jdp_away_clicks_agg_last_seven_days,
        seo_ab_prod_metrics_job,
        ext_stat_away_match_job,
        additional_pages_click_daily_agg_job,
        info_region_other_job,
        account_agg_job,
        adv_revenue_by_placement_and_src_job,
        adv_revenue_by_placement_and_src_analytics_agg_job,
        funnel_agg_job,
        dic_info_project_discount_job,
        dic_info_project_discount_monthly_job,
        jobs_stat_hourly_job,
        # auction_external_stat_job,
        campaign_auto_esc_stopped_job,
        banner_stat_history_job,
        banner_filter_job,
        banner_info_job,
        banner_limit_job,
        info_currency_history_job,
        project_job_apply_agg_job,
        project_job_type_agg_job,
        project_tracking_setting_job,
        conversion_job,
        conversion_action_job,
        general_feed_ignored_projects_job,
        # general_feed_ignored_companies_job,
        user_budget_log_job,
        campaign_log_yesterday_date_job,
        campaign_log_current_date_job,
        user_log_job,
        banner_stat_today_job,
        # innovation_adsy_project_job,
        session_feature_job,
        # field_from_source_daily_job,
        campaign_job,
        account_contact_job,
        campaign_feature_job,
        client_daily_settings_job,
        site_job,
        site_manager_job,
        auction_user_job,
        scheduled_operation_job,
        auction_job_multiplication_job,
        session_test_job,
    ],
    sensors=[
        monitor_all_jobs_sensor,
        session_daily_agg_sensor,
    ],
)
