from dagster import (
    Definitions
)

# IMPORT SENSORS
from .sensors import *

# IMPORT SCHEDULES, ASSETS, JOBS
from .jobs_schedules import *

# define all: op, assets, jobs and schedules
defs = Definitions(
    schedules=[
        schedule_prc_insert_public_push_firebase_subscriptions,
        schedule_session_revenue_by_placement,
        # schedule_account_revenue_abtest,
        schedule_action_agg,
        schedule_job_categories,
        schedule_insert_emails_yesterday_date,
        schedule_vacancy_collars,
        schedule_serp_rivals_agg,
        schedule_clicks_collars,
        schedule_product_metrics_agg,
        schedule_search_agg_abtest_agg,
        ### rpl jobs snapshots
        schedule_ins_job_snapshot,
        schedule_job_region_snapshot,
        schedule_info_currency_snapshot,
        schedule_campaign_log_snapshot,
        schedule_prc_imp_account_revenue_job_current_date,
        # schedule_prc_imp_account_revenue_job_yesterday_date,
        schedule_click_metric_agg_yesterday_date,
        schedule_click_metric_agg_current_date,
        ### /rpl jobs snapshots
        schedule_job_history_snapshot_yesterday_date,
        schedule_job_history_snapshot_current_date,
        schedule_sentinel_statistic,
        # schedule_account_revenue,
        schedule_impression_statistic,
        schedule_recommendations_agg,
        # schedule_registration_email_funnel,
        # schedule_letter_job_click,
        schedule_itc_jdp,
        schedule_cv_information_agg,
        schedule_ea_search_conversion,
        schedule_prc_tmp_session_tables_materialise,
        schedule_insert_emails_job_current_date,
        # schedule_project_conversions_daily_reload_two_days,
        # schedule_project_conversions_daily_reload_five_days,
        schedule_conversion_daily_check,
        schedule_balkans_job_stats,
        schedule_balkans_session_cnt_by_traff_source,
        schedule_balkans_user_metrics_by_traff_source,
        schedule_vacancy_job_search_prod_agg,
        schedule_aoj_apply_action_agg,
        schedule_session_feature_action,
        schedule_email_metric_daily,
        schedule_client_job_dynamics,
        schedule_serp_campaign_rivals_agg,
        schedule_mobile_app_install_info,
        schedule_mobile_session,
        schedule_mobile_session_feature,
        schedule_mobile_session_feature_action,
    ],
    assets=[],
    jobs=[
        prc_insert_public_push_firebase_subscriptions_job,
        click_metric_agg_trino_job,
        prc_first_launch_attribute_job,
        session_revenue_by_placement_job,
        action_agg_job,
        account_revenue_abtest_agg_job,
        job_categories_job,
        insert_emails_job_yesterday_date,
        vacancy_collars_job,
        serp_rivals_agg_job,
        clicks_collars_job,
        product_metrics_agg_job,
        search_agg_abtest_agg_job,
        ### rpl jobs snapshots
        prc_insert_job_snapshot_job,
        prc_insert_job_region_snapshot_job,
        prc_insert_info_currency_snapshot_job,
        prc_insert_campaign_log_snapshot_job,
        prc_click_metric_agg_job_yesterday_date,
        prc_click_metric_agg_job_current_date,
        ### /rpl jobs snapshots
        email_abtest_agg_job_yesterday_date,
        prc_insert_job_history_snapshot_job_yesterday_date,
        prc_insert_job_history_snapshot_job_current_date,
        sentinel_statistic_job,
        account_revenue_job,
        impression_statistic_job,
        recommendations_agg_job,
        # registration_email_funnel_job,
        # letter_job_click,
        itc_jdp,
        cv_information_agg_job,
        ea_search_conversion_job,
        prc_tmp_session_tables_materialise_job,
        email_abtest_agg_job_current_date,
        insert_emails_job_current_date,
        prc_imp_account_revenue_job_current_date,
        prc_imp_account_revenue_job_yesterday_date,
        session_abtest_agg_new_job_yesterday_date,
        session_abtest_agg_new_job_current_date,
        # project_conversions_daily_reload_two_days_job,
        # project_conversions_daily_reload_five_days_job,
        conversion_daily_check_job,
        email_abtest_agg_by_account_job_yesterday_date,
        email_abtest_agg_by_account_job_current_date,
        balkans_job_stats_job,
        balkans_session_cnt_by_traff_source_job,
        balkans_user_metrics_by_traff_source_job,
        email_abtest_account_agg_job,
        vacancy_job_search_prod_agg_job,
        mobile_app_business_metrics_job,
        mobile_app_activity_metrics_dau_job,
        mobile_app_activity_metrics_wau_job,
        mobile_app_activity_metrics_mau_job,
        aoj_apply_action_agg_job,
        apply_conversion_service_job,
        session_feature_action_job,
        email_metric_daily_job,
        mobile_app_push_metrics_job,
        email_spam_report_agg_job,
        client_job_dynamics_job,
        client_job_dynamics_h_job,
        serp_campaign_rivals_agg_job,
        mobile_app_install_info_job,
        mobile_app_install_info_temp_to_replica_job,
        mobile_session_job,
        mobile_session_feature_job,
        mobile_session_feature_action_job,
    ],
    sensors=[
        finance_report_sensor,
        click_metric_agg_job_yesterday_date_sensor,
        click_metric_agg_job_current_date_sensor,
        click_data_agg_job_sensor,
        email_abtest_agg_job_yesterday_date_sensor,
        email_abtest_agg_job_current_date_sensor,
        email_abtest_account_agg_job_sensor,
        email_abtest_agg_by_account_job_yesterday_date_sensor,
        email_abtest_agg_by_account_job_current_date_sensor,
        session_abtest_agg_run_main_metrics_job_sensor,
        budget_revenue_daily_agg_job_sensor,
        cabacus_sensor,
        monitor_all_jobs_sensor,
        prc_imp_account_revenue_job_yesterday_date_sensor,
        account_revenue_job_sensor,
        account_revenue_abtest_agg_job_sensor,
        mobile_app_business_metrics_job_sensor,
        mobile_app_activity_metrics_dau_job_sensor,
        mobile_app_activity_metrics_wau_job_sensor,
        mobile_app_activity_metrics_mau_job_sensor,
        mobile_app_push_metrics_job_sensor,
        email_spam_report_agg_job_sensor,
        mobile_app_first_launch_attribute_job_sensor,
    ],
)
